Version 0.15.0
vitrivr/cottontaildb pull request #111
Opened 2022-04-22 10:23 UTC by ppanopticon

This is the pull request in preparation of the release of v0.15.0 of Cottontail DB, which mainly features:

- A new storage engine based on JetBrains Xodus
- Improved intra-query parallelism
- Working versions of VAF and PQ index structures

2022-04-22 12:13 UTC, ppanopticon commented
All unit tests succeed. 

Furthermore, I did run all Cineast unit tests of the `feature/poseQueries` branch against this version and after a few minor fixes, they all pass.

2022-04-22 14:29 UTC, lucaro requested changes
I gave up looking through all the files at some point, but I found some minor issues

2022-04-22 14:29 UTC, lucaro commented on cottontaildb-dbms/src/main/kotlin/org/vitrivr/cottontail/config/CostConfig.kt
> +        require((this.wio + this.wcpu + this.wmemory + this.waccuracy) == 1.0f) { "All cost weights must add-up to 1.0 but add up to ${this.wio + this.wcpu + this.wmemory + this.waccuracy}."}
same as before

2022-04-22 14:29 UTC, lucaro commented on cottontaildb-dbms/src/main/kotlin/org/vitrivr/cottontail/dbms/general/DBOVersion.kt
> +    /** The second, iteration of the Cottontail DB file organisation which was introduced in preparation of the HARE column format. */
copy pasta

2022-04-22 14:29 UTC, lucaro commented on cottontaildb-dbms/src/main/kotlin/org/vitrivr/cottontail/dbms/index/AbstractHDIndex.kt
> +                /* TODO: Process. */
TODO?

2022-04-22 14:40 UTC, ppanopticon commented on cottontaildb-core/src/main/kotlin/org/vitrivr/cottontail/core/values/ShortValue.kt
> +        val MAX_VALUE = ShortValue(Int.MAX_VALUE)
Fixed

2022-04-22 14:40 UTC, ppanopticon commented on cottontaildb-cli/src/main/kotlin/org/vitrivr/cottontail/Playground.kt
> +fun main(args: Array<String>) {
No. Removed it... :-)

2022-04-22 14:43 UTC, ppanopticon commented on cottontaildb-dbms/build.gradle
> +    implementation group: 'org.apache.lucene', name: 'lucene-analyzers-phonetic', version: '8.11.1'
You're right! I missed those two since the packets were renamed with Lucene 9.0

Fixed!

2022-04-22 14:49 UTC, lucaro commented on cottontaildb-core/src/main/kotlin/org/vitrivr/cottontail/core/queries/QueryHint.kt
> +            require((this.wio + this.wcpu + this.wmemory + this.waccuracy) == 1.0f) { "All cost weights must add-up to 1.0 but add up to ${this.wio + this.wcpu + this.wmemory + this.waccuracy}."}
how about something like
```kotlin
require( abs((this.wio + this.wcpu + this.wmemory + this.waccuracy) - 1.0f) < 1e-6 ) { ... }
```

2022-04-22 14:55 UTC, lucaro approved these changes
👍

2022-04-25 19:19 UTC, silvanheller approved these changes
I approve wholeheartedly - this results in significant speedups across the board. Thanks for the huge amount of work!

2022-04-26 05:04 UTC, merged